name: Release

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch or tag name
        id: ref
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//};
            echo "VERSION=${VERSION#v}" >> $GITHUB_ENV
          else
            VERSION=${GITHUB_REF/refs\/heads\//}
            echo "VERSION=${VERSION#v}" >> $GITHUB_ENV
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Update version
        run: |
          poetry version ${{ env.VERSION }}
          
          git config --global user.name "newspy"
          git config --global user.email "newspy@youremail.com"
          
          git add pyproject.toml
          git commit -m "chore: bump version to ${{ env.VERSION }}"
          git push origin main

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
